"""empty message

Revision ID: 5204748f5e4c
Revises: 93e3175f492e
Create Date: 2026-05-19 15:59:07.022544

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5204748f5e4c'
down_revision = '93e3175f492e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('luma_export_job',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('download_url', sa.Text(), nullable=True),
    sa.Column('ee_image_serialized', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('email_requested', sa.Boolean(), nullable=True),
    sa.Column('requester_email', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['user_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('luma_export_job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_luma_export_job_session_id'), ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('luma_export_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_luma_export_job_session_id'))

    op.drop_table('luma_export_job')
    # ### end Alembic commands ###
