"""empty message

Revision ID: 6fee4dd0fd38
Revises: ffc73560f605
Create Date: 2026-02-14 09:48:32.463028

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision = '6fee4dd0fd38'
down_revision = 'ffc73560f605'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('luma_general',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('landsat_version', sa.String(length=10), nullable=True),
    sa.Column('cloud_cover', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['user_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('luma_general', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_luma_general_session_id'), ['session_id'], unique=False)

    op.create_table('luma_layers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['user_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('luma_layers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_luma_layers_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_luma_layers_session_id'), ['session_id'], unique=False)

    op.create_table('luma_lulc_class',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('class_name', sa.String(length=256), nullable=True),
    sa.Column('class_color', sa.String(length=20), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['user_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('luma_lulc_class', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_luma_lulc_class_session_id'), ['session_id'], unique=False)

    op.create_table('luma_training_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('class_name', sa.String(length=256), nullable=True),
    sa.Column('class_color', sa.String(length=20), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['user_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('luma_training_data', schema=None) as batch_op:
        # batch_op.create_index('idx_luma_training_data_geom', ['geom'], unique=False, postgresql_using='gist')
        batch_op.create_index(batch_op.f('ix_luma_training_data_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('luma_training_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_luma_training_data_session_id'))
        # batch_op.drop_index('idx_luma_training_data_geom', postgresql_using='gist')

    op.drop_table('luma_training_data')
    with op.batch_alter_table('luma_lulc_class', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_luma_lulc_class_session_id'))

    op.drop_table('luma_lulc_class')
    with op.batch_alter_table('luma_layers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_luma_layers_session_id'))
        batch_op.drop_index(batch_op.f('ix_luma_layers_code'))

    op.drop_table('luma_layers')
    with op.batch_alter_table('luma_general', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_luma_general_session_id'))

    op.drop_table('luma_general')
    # ### end Alembic commands ###
