"""empty message

Revision ID: 93e3175f492e
Revises: ea3d54732609
Create Date: 2026-05-17 22:10:04.088411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93e3175f492e'
down_revision = 'ea3d54732609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullname', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('organization_name', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('signup_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('signup_token_expires', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint(None, ['signup_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('is_active')
        batch_op.drop_column('signup_token_expires')
        batch_op.drop_column('signup_token')
        batch_op.drop_column('organization_name')
        batch_op.drop_column('fullname')

    # ### end Alembic commands ###
