"""add system_error_log

Revision ID: b4289b175e3c
Revises: 6fee4dd0fd38
Create Date: 2026-03-26 00:06:08.892291

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b4289b175e3c'
down_revision = '6fee4dd0fd38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_error_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('api_name', sa.String(length=256), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('request_url', sa.Text(), nullable=True),
    sa.Column('request_method', sa.String(length=16), nullable=True),
    sa.Column('request_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trace', sa.Text(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_error_log')
    # ### end Alembic commands ###
