"""empty message

Revision ID: ea3d54732609
Revises: 0c39408da59b
Create Date: 2026-05-17 18:38:52.391636

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ea3d54732609'
down_revision = '0c39408da59b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('luma_general', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spatial_resolution', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ntrees', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('min_leaf', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('predictor_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('use_predictor', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('luma_general', schema=None) as batch_op:
        batch_op.drop_column('use_predictor')
        batch_op.drop_column('predictor_config')
        batch_op.drop_column('min_leaf')
        batch_op.drop_column('ntrees')
        batch_op.drop_column('spatial_resolution')
    # ### end Alembic commands ###
