"""empty message

Revision ID: f8ba716a9f4c
Revises: a46391445b65
Create Date: 2025-08-01 03:26:29.800542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8ba716a9f4c'
down_revision = 'a46391445b65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geos_lulc_classification',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('start_date', sa.String(length=10), nullable=True),
    sa.Column('end_date', sa.String(length=10), nullable=True),
    sa.Column('landsat_version', sa.String(length=10), nullable=True),
    sa.Column('cloud_cover', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['user_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('geos_lulc_classification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_geos_lulc_classification_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geos_lulc_classification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_geos_lulc_classification_session_id'))

    op.drop_table('geos_lulc_classification')
    # ### end Alembic commands ###
