"""empty message

Revision ID: ffc73560f605
Revises: 1b5a0abbe012
Create Date: 2025-08-03 08:38:08.006504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffc73560f605'
down_revision = '1b5a0abbe012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_gee_asset',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=256), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['user_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_gee_asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_gee_asset_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('geos_lulc_classification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('training_asset_id', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geos_lulc_classification', schema=None) as batch_op:
        batch_op.drop_column('training_asset_id')

    with op.batch_alter_table('user_gee_asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_gee_asset_session_id'))

    op.drop_table('user_gee_asset')
    # ### end Alembic commands ###
